{
 "title": "Container Performance Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Container Hardware Activity",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 17, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cpu_percent", "legendFormat": "CPU Use Percentage" },
    { "expr": "disk_percent", "legendFormat": "Disk Use Percentage" },
    { "expr": "memory_percent", "legendFormat": "Memory Use Percentage" }
   ]
  },
  {
   "title": "Container Network Activity",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "network_bytes_recv", "legendFormat": "Network Bytes Received" },
    { "expr": "network_bytes_sent", "legendFormat": "Network Bytes Sent" }
   ]
  },
  {
   "title": "Container Health",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "container_health", "legendFormat": "__auto" }
   ]
  }
 ]
}